### ISSUE TITLE
Request for Prompt Setup and Complete Testing Code for 5 Tasks

### ISSUE THREAD

**Issue by rippleD030** [facebookresearch/chai#2]
Dear authors,

hope you are doing well. I am currently working with the LLaMA 7B model to replicate results for the tasks in Evaluation.
However, I am facing difficulties in designing effective prompts for these tasks, leading to suboptimal model performance. I would greatly appreciate it if you could provide the complete testing code or share the specific prompt setup used in your paper for these tasks. Any further guidance or tips on improving the model's performance would also be very helpful.

Thank you for your time and support. I look forward to your response.

**Comment by iidsample** [comment]
We do not use any specific prompting for the tasks. 
I will work on integrating our setup with open source LLM eval harness as the code used for paper uses an internal Meta version for evaluation.
